### ISSUE TITLE
ML.Dev.Prog.Sig ，no package called ‘gbm’ error

### ISSUE THREAD

**Issue by yan-ziwei** [l-magnificence/Mime#13]
When I run the sample data I get
res <- ML.Dev.Prog.Sig(train_data = list_train_vali_Data$Dataset1,
                     list_train_vali_Data = list_train_vali_Data,
                     unicox.filter.for.candi = T,
                     unicox_p_cutoff = 0.05,
                     candidate_genes = genelist,
                     mode = 'all',nodesize =5,seed = 5201314 )

Error in checkForRemoteErrors(val) : 
  6 nodes produced errors; first error: there is no package called ‘gbm’

But I have installed the R package library(gbm)，And successfully loaded

**Comment by l-magnificence** [comment]
We have changed the package name to Mime1, please reinstall using below and retry.
```
devtools::install_github("l-magnificence/Mime")
```

**Comment by ksjsy1996926** [comment]
Thank you very much for your help. However, even after downloading the new version, I encountered a similar problem:
Error in checkForRemoteErrors(val) : 
  6 nodes produced errors; first error: there is no package called 'gbm'
I have already installed the package 'gbm' and ‘Mime1’, but the program still cannot run.

**Comment by ksjsy1996926** [comment]
Successfully loaded the gbm package after the latest modification. Thank you very much!
