### ISSUE TITLE
ML.Dev.Pred.Category.Sig error

### ISSUE THREAD

**Issue by PanSX-Dr** [l-magnificence/Mime#14]
Hello, first of all, thank you very much for your urgent feedback on my problem. But now, I have had a new problem.
when I run the function: 
res.ici <- ML.Dev.Pred.Category.Sig(train_data = list_train_vali_Data$training,
                                    list_train_vali_Data = list_train_vali_Data,
                                    candidate_genes = genelist,
                                    methods = c('nb','svmRadialWeights','rf','kknn','adaboost','LogitBoost','cancerclass'),
                                    seed = 5201314,
                                    cores_for_parallel = 60
)#报错。
 in showed the error:
Start analyse...
Finished!
[1] "cancerclass"
错误于if (class(model.tune) == "predictor") {: 
  the condition has length > 1
此外: 警告信息:
In randomForest.default(x, y, mtry = param$mtry, ...) :
  invalid mtry: reset to within valid range
but I have installed the package.

**Comment by ydx1013** [comment]
olnames found in data matrix...
Read and prepare data...
  Info (dataset): 42x70
  #N/#Y: 49/21
  Method: welch.test

Start analyse...
Finished!
[1] "cancerclass"
错误于if (class(model.tune) == "predictor") {: 
  the condition has length > 1

**Comment by l-magnificence** [comment]
Install cancerclass version 1.38.0 and retry to see if the error still exist

**Comment by l-magnificence** [comment]
We have made some modification, please reinstall and retry.

**Comment by l-magnificence** [comment]
Duplicate of #17
