### ISSUE TITLE
TME_deconvolution_all function error

### ISSUE THREAD

**Issue by kestlermai** [l-magnificence/Mime#15]
```library(immunedeconv)```

`devo <- TME_deconvolution_all(list_train_vali_Data)`

--- Data preprocessing ---
Error in select(., -c(ID, OS.time, OS)) : 
  unused argument (-c(ID, OS.time, OS))
  

> sessionInfo()

other attached packages:
 [1] magrittr_2.0.3        immunedeconv_2.1.0    EPIC_1.1.7            forestploter_1.1.1    meta_7.0-0           
 [6] metadat_1.2-0         lubridate_1.9.3       forcats_1.0.0         stringr_1.5.1         purrr_1.0.2          
[11] readr_2.1.5           tidyverse_2.0.0       survivalROC_1.0.3.1   survminer_0.4.9       ggpubr_0.6.0         
[16] aplot_0.2.2           risksetROC_1.0.4.1    data.table_1.15.4     mixOmics_6.24.0       lattice_0.22-5       
[21] MASS_7.3-60.0.1       ggbreak_0.1.2         tidyr_1.3.1           ggsci_3.0.3           ggplot2_3.5.0        
[26] compareC_1.3.2        miscTools_0.6-28      BART_2.9.9            nlme_3.1-164          tibble_3.2.1         
[31] dplyr_1.1.4           survivalsvm_0.0.5     CoxBoost_1.5          prodlim_2023.08.28    gbm_2.2.2            
[36] superpc_1.12          plsRcox_1.7.7         glmnet_4.1-8          randomForestSRC_3.3.0 survival_3.5-8       
[41] Matrix_1.6-5          Mime1_0.0.0.9000

**Comment by l-magnificence** [comment]
This is not an error of the function. Please check the format of input data.

**Comment by kestlermai** [comment]
Oh！thanks, it's working.

**Comment by weifuq** [comment]
![image](https://github.com/user-attachments/assets/3d332032-0d9f-4d1f-b2e4-612ec25f91d3)
![image](https://github.com/user-attachments/assets/431e8f28-c9de-4ccf-b191-2e63390efa47)

**Comment by l-magnificence** [comment]
Due to that immune microenvironment deconvolution are processed by R package immunedeconv (https://github.com/omnideconv/immunedeconv), you can try use this package directly and see if it can run successfully and contact them for issue.

**Comment by l-magnificence** [comment]
> ![image](https://private-user-images.githubusercontent.com/154768214/350901194-3d332032-0d9f-4d1f-b2e4-612ec25f91d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mzg5NzUsIm5iZiI6MTcyMTYzODY3NSwicGF0aCI6Ii8xNTQ3NjgyMTQvMzUwOTAxMTk0LTNkMzMyMDMyLTBkOWYtNGQxZi1iMmU0LTYxMmVjMjVmOTFkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwODU3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjY1ZjE3ZTg2N2RiOTUwZjRmYWI2ZDcyM2U1N2RlNjUzYTI5MWYxMDM4ZTg3Zjk1NDRhY2NmMjczMzk5NjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zF8rl9ggVu_N4Nfo2juf01gwO1CvRc57l553Vc91erc) ![image](https://private-user-images.githubusercontent.com/154768214/350901814-431e8f28-c9de-4ccf-b191-2e63390efa47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mzg5NzUsIm5iZiI6MTcyMTYzODY3NSwicGF0aCI6Ii8xNTQ3NjgyMTQvMzUwOTAxODE0LTQzMWU4ZjI4LWM5ZGUtNGNjZi1iMTkxLTJlNjMzOTBlZmE0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwODU3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjNhMTk4OWY2MjY0MDA3Mjg2YjdjYmI5NjZjODIyY2JhMDUyMmM1NmIxODFhYTQxMDViZGZlZTQxZDQ0OGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tza0nx5RPD26r7zRncGsPxWGQonzyR4Sg3Oxfbougi4)

Due to that immune microenvironment deconvolution are processed by R package immunedeconv (https://github.com/omnideconv/immunedeconv), you can try use this package directly and see if it can run successfully and contact them for issue.

**Comment by 123wanguang123456** [comment]
> Oh！thanks, it's working.

@kestlermai 

Hello, how to solve this error?

--- Data preprocessing ---
Error in select(., -c(ID, OS.time, OS)) :
unused argument (-c(ID, OS.time, OS))

**Comment by kestlermai** [comment]
> > Oh！thanks, it's working.
> 
> @kestlermai
> 
> Hello, how to solve this error?
> 
> --- Data preprocessing --- Error in select(., -c(ID, OS.time, OS)) : unused argument (-c(ID, OS.time, OS))
@l-magnificence @123wanguang123456 
Hey, After debugging, I found that there’s a conflict between the cal_AUC_ml_res function and the TME_deconvolution_all function. I think it’s due to some package conflicts, maybe the dplyr package. So, you need to restart your R Studio, reload the Mime1 and immunedeconv packages, and then directly run TME_deconvolution_all function. It should work fine then.

**Comment by 123wanguang123456** [comment]
@kestlermai Thank you for your careful answer. I have done so according to what you said, but I still report this error. Is there any good way?

> devo <- TME_deconvolution_all(list_train_vali_Data)
--- Data preprocessing ---
Error in select(., -c(ID, OS.time, OS)) : 
  unused argument (-c(ID, OS.time, OS))

**Comment by l-magnificence** [comment]
@123wanguang123456  Please reinstall and retry.

**Comment by rayrayhuang** [comment]
> Hello, how to solve this error?

**Comment by rayrayhuang** [comment]
> ![image](https://private-user-images.githubusercontent.com/154768214/350901194-3d332032-0d9f-4d1f-b2e4-612ec25f91d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTc3NDcsIm5iZiI6MTcyMTkxNzQ0NywicGF0aCI6Ii8xNTQ3NjgyMTQvMzUwOTAxMTk0LTNkMzMyMDMyLTBkOWYtNGQxZi1iMmU0LTYxMmVjMjVmOTFkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxNDI0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2ZkYTcwNmMzYmM0NzkwN2E4ZWU2NTJlNTJmNDdlNjVkMGFmOTE1NzVlNGM0MDRlM2I3ZDdlYjM4ZjY2ZjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zbJRlrAxVxpPGSYcbm_SV5ykvaRIatqNox1IF68cZMg) ![image](https://private-user-images.githubusercontent.com/154768214/350901814-431e8f28-c9de-4ccf-b191-2e63390efa47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTc3NDcsIm5iZiI6MTcyMTkxNzQ0NywicGF0aCI6Ii8xNTQ3NjgyMTQvMzUwOTAxODE0LTQzMWU4ZjI4LWM5ZGUtNGNjZi1iMTkxLTJlNjMzOTBlZmE0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxNDI0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGYwYTdlZDY5YWU3ODEzOWQxNWNmMGFiM2U4YjgyZGZmM2EzYjQ5M2Q4Y2VmNmMzOTc0ZmQxMjFkZWIzMjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rulFpM0iK5HCjhPJTgKuXTgal7Cb_hGyEYFKvYcxwkU)

Hello, how to solve this error?

**Comment by l-magnificence** [comment]
@rayrayhuang  Have you reinstalled and retry??? We have made some updates.

**Comment by rayrayhuang** [comment]
> @rayrayhuang Have you reinstalled and retry? We have made some updates.
I reinstalled the package and still reported this error

**Comment by l-magnificence** [comment]
@rayrayhuang I'm confused that this shouldn't happen in the latest version. If you still want it, I recommend you do the analysis yourself directly using the R package immuneconv.
