### ISSUE TITLE
Lasso + GBM function error

### ISSUE THREAD

**Issue by kerwin223** [l-magnificence/Mime#19]
When running the Lasso + GBM model, the process gets interrupted:
res <- ML.Dev.Prog.Sig(
  train_data = list_train_vali_Data$train_data,
  list_train_vali_Data = list_train_vali_Data,
  unicox.filter.for.candi = TRUE,
  unicox_p_cutoff = 0.05,
  candidate_genes = my_genelist,
  mode = 'all',
  nodesize = 5,
  seed = 5201314
)
![70e38c9556e3dd8f16b1de8c19111f9](https://github.com/l-magnificence/Mime/assets/54584775/60b23576-2ede-4538-82ec-b9c8ed321a08)
![2f5e78ab9bd21686d47f025d74fe214](https://github.com/l-magnificence/Mime/assets/54584775/b604cfc4-3554-4b5a-a824-d1b6032ba8c3)
![e8563fd4e17bc04cc908d87daaabd49](https://github.com/l-magnificence/Mime/assets/54584775/4231abdb-5cae-4c51-999c-bdc1a82a0fd2)
![35099f7dab8144f238029c89f4373f9](https://github.com/l-magnificence/Mime/assets/54584775/0ce5fab6-b965-4a49-bd50-b24a9f26a6d7)

**Comment by l-magnificence** [comment]
I think this may be due to the fact that too few genes are selected for model construction. Can you add more genes for model 
construction and see if the error still exist.

**Comment by kerwin223** [comment]
> I think this may be due to the fact that too few genes are selected for model construction. Can you add more genes for model construction and see if the error still exist.

Appreciate！It works! Additional question: I tried building the model with 60 genes for the first time, but it failed. Is 60 the minimum number of genes required for the model?

**Comment by l-magnificence** [comment]
Because you set unicox_p_cutoff = 0.05, so Mime will firstly filter genes associated with prognosis from your input gene list. If there are little genes meeting this criteria from 60 genes, it will be hard to construct models.
By the way, you can also try set unicox.filter.for.candi=F to directly construct models from 60 genes.

**Comment by kerwin223** [comment]
> Because you set unicox_p_cutoff = 0.05, Mime will firstly filter genes associated with prognosis from your input gene list. If there are little genes meeting this criteria from 60 genes, it will be hard to construct models. By the way, you can also try set unicox.filter.for.candi=F to directly construct models from 60 genes.

Got it. Thanks for patiently explaining.
