### ISSUE TITLE
老铁，“具体”的模型如何得到？

### ISSUE THREAD

**Issue by doclihan** [l-magnificence/Mime#21]
老铁，你这个包真不赖！构建出响应模型（二分类模型）后，我还有几个问题：
1.构建的模型算出来的预测值如何得到，因为我想拿来做进一步的分析。但是鉴于水平有限，我没法从您的代码中得到预测值。
2.我想用shap解释机器学习的黑匣子，但是我不知道怎么“找到”模型（虽然已经构建出来了）
最后再次感谢您！

**Comment by l-magnificence** [comment]
The detailed information of each model are stored in the output by ML.Dev.Pred.Category.Sig, such as 
```
res.ici[["model"]][["nb"]]
```
you can use function of predict to get predicted value 
```
pre <- predict(res.ici[["model"]][["nb"]], list_train_vali_Data[["validation"]][, -1])
```
Here the structure of cancerclass is different from other models, you need to use the function of predict from package cancerclass and see how to use it in its manual.

**Comment by doclihan** [comment]
Thanks for your unselfless help!
Is there a manual of Mime1 specially to guide our practice? It would be very very helpful!
