### ISSUE TITLE
terminate called after throwing an instance of 'std::length_error'   what():  vector::_M_default_append terminate called after throwing an instance of 'std::length_error'   what():  vector::_M_default_append Error in unserialize(node$con) : error reading from connection

### ISSUE THREAD

**Issue by yandouwahhh** [l-magnificence/Mime#23]
when i run the following code, error happen.
code：
res <- ML.Dev.Prog.Sig(train_data = trainlist$train,
                       list_train_vali_Data = trainlist,
                       unicox.filter.for.candi = T,
                       unicox_p_cutoff = 0.05,
                       candidate_genes = genelist,
                       mode = 'all',nodesize =1,seed = 5201314 )
error:
---1-4.RSF + GBM ---
minimal depth variable selection ...

-----------------------------------------------------------
family             : surv 
var. selection     : Minimal Depth 
conservativeness   : high 
x-weighting used?  : TRUE 
dimension          : 6 
sample size        : 97 
ntree              : 1000 
nsplit             : 10 
mtry               : 3 
nodesize           : 1 
refitted forest    : FALSE 
model size         : 6 
depth threshold    : 4.5115 
PE (true OOB)      : 29.186 

Top variables:
           depth  vimp
VWA1       1.720 0.095
EFNA3      1.757 0.122
BTBD16     1.963 0.061
AC117386.2 2.273 0.041
WFDC10A    2.515 0.031
CAPS       2.557 0.016
-----------------------------------------------------------
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Error in unserialize(node$con) : error reading from connection

I looked at some other serialization (node $con) and Unerialialize(Node $con) error posts, but they didn't seem to help me.
Looking forward to your reply!

**Comment by l-magnificence** [comment]
see #26
