### ISSUE TITLE
Is categorical variables available?

### ISSUE THREAD

**Issue by doclihan** [l-magnificence/Mime#28]
Thanks for you contribution! 
I have trouble with the type of input data. 
I specially changed the **data type from ”double“ to '”factor“**, and Mime could work normally. However, when I further ranked the importance of variables, **all continuous variables were more important than categorical variables**, which was obviously wrong with clinical practice and previous logistic analysis. Then we carefully analyze your code and find that when building the model, the **Mime package automatically converts** the factorl variable into a numerical form.
**Hence, how should I correctly use both categorical variables and continuous variables to build the model ?**

**Comment by l-magnificence** [comment]
Currently, Mime only support numerical matrices data. Thank you.

**Comment by doclihan** [comment]
What happens after I code a categorical variable?

**Comment by l-magnificence** [comment]
I haven't tried. If your categorical variables are grade factor, maybe you can change them to numerical variables, such as 0,1,2,3 to run.

**Comment by doclihan** [comment]
Thank you, I'll try it.
