### ISSUE TITLE
How do you view the contents of the risk model

### ISSUE THREAD

**Issue by yandouwahhh** [l-magnificence/Mime#29]
Hi,
After I run through the steps of building a prognostic prediction model, how do I know the specific model built by a combination of machine learning methods?
eg:n1*gene1+n2*gene2+n3*gene3...
Look forward to your reply!

**Comment by l-magnificence** [comment]
see #21

**Comment by yandouwahhh** [comment]
Hi,
Maybe I didn't make myself clear. What I want to know is the formula. Eg: risk score = (0.246026 × CDKN1A) + (0.359130 × CTSD) + (0.234375 × CTSL) + (0.590736 × EIF4EBP1) + (−0.281261 × TMEM74) + (0.338378 × VAMP3). Is there any way to find out
