### ISSUE TITLE
Can “Mime” packages run data with a gene expression of "0"?

### ISSUE THREAD

**Issue by 123wanguang123456** [l-magnificence/Mime#31]
Dear author,

I run a data that has some gene expression "0" and get an error: “Error in serialize(data, node$con) : error writing to connection”.
What should be done in this situation? Thank you!

maximum partial log-likelihood at boosting step 60
--- 3.StepCox[backward] + Enet[α=0.1] ---
--- 3.StepCox[backward] + Enet[α=0.2] ---
--- 3.StepCox[backward] + Enet[α=0.3] ---
--- 3.StepCox[backward] + Enet[α=0.4] ---
--- 3.StepCox[backward] + Enet[α=0.5] ---
--- 3.StepCox[backward] + Enet[α=0.6] ---
--- 3.StepCox[backward] + Enet[α=0.7] ---
--- 3.StepCox[backward] + Enet[α=0.8] ---
--- 3.StepCox[backward] + Enet[α=0.9] ---
--- 3.StepCox[backward] + GBM ---
Error in serialize(data, node$con) : error writing to connection
In addition: There were 18 warnings (use warnings() to see them)
Error in serialize(data, node$con) : error writing to connection

**Comment by l-magnificence** [comment]
Some gene expression "0" don't influence work. Please reinstall and set cores_for_parallel=1 to see if it can run, such as:
```
res= ML.Dev.Prog.Sig(train_data = list_train_vali_Data$Dataset1,
                     list_train_vali_Data = list_train_vali_Data,
                     unicox.filter.for.candi = T,
                     unicox_p_cutoff = 0.05,
                     candidate_genes = genelist,
                     mode = 'all',
                     nodesize =5,seed = 5201314,
                     cores_for_parallel=1)
```

**Comment by l-magnificence** [comment]
Please see #26
