### ISSUE TITLE
How can I get risk score formula of each model?

### ISSUE THREAD

**Issue by Zeral-leo** [l-magnificence/Mime#32]
excuse me, I want to get risk score formula of all models,like Risk score = 0.16× expression of A −0.08× expression of B+ 0.14× expression of C + ...........
how can I get this from "allModel.RData"  or other files after run "ML.Dev.Prog.Sig()" ? Think you!

**Comment by Zeral-leo** [comment]
lasso and stepcox....has coefficients,but others? like RSF.......

**Comment by l-magnificence** [comment]
As you know, not all model is simply defined as the sum of coefficient*expression. You need to learn the detailed structure of specific model from original method and extract information from output by "ML.Dev.Prog.Sig". Also if you want get risk score, you can use function "cal_RS_ml_res".
