### ISSUE TITLE
When using the sample data, it can run successfully, but when using my own data, the gbm step does not produce results for a long time, and error  occured

### ISSUE THREAD

**Issue by yandouwahhh** [l-magnificence/Mime#34]
![微信图片_20240717144313](https://github.com/user-attachments/assets/1ccdd956-6b4f-4ec9-9095-292bc43fa549)

There seems to be a problem when it comes to gbm methods.It's not like a mistake because the data is too big

my data:
>dim(list_train_vali_Data$Dataset1)
[1] 112  20
> dim(list_train_vali_Data$Dataset2)
[1] 107  20
> list_train_vali_Data$Dataset1[1:4,1:5]
                             ID OS.time OS   FKBP10    TPPP3
1 TCGA.A1.A0SK.01A     967  1 5.049623 4.615698
2 TCGA.A1.A0SP.01A     584  0 6.835768 4.319503
3 TCGA.A2.A04U.01A    2654  0 6.610821 3.443134
4 TCGA.A2.A0CM.01A     754  1 5.602947 2.746017
> list_train_vali_Data$Dataset2[1:4,1:5]
                    ID OS.time OS       BGN     CHPF
1 GSM1419942    1520  1 10.207883 7.977907
2 GSM1419943    1281  1  8.707468 6.584553
3 GSM1419944    1066  1  9.402426 6.861479
4 GSM1419945    1050  1 10.449300 6.938301

**Comment by l-magnificence** [comment]
If your environment don't support multicore and you run this process in the condition of 1 core, it may run for a long time.
Besides we recommend gene set with more than 50 genes.

**Comment by yandouwahhh** [comment]
Thanks for your reply. I will try it.
