### ISSUE TITLE
Error in serialize(data, node$con) : error writing to connection

### ISSUE THREAD

**Issue by 123wanguang123456** [l-magnificence/Mime#36]
Dear Author:  What does this error mean?

maximum partial log-likelihood at boosting step 163 
--- 3.StepCox[backward] + Enet[α=0.1] ---
--- 3.StepCox[backward] + Enet[α=0.2] ---
--- 3.StepCox[backward] + Enet[α=0.3] ---
--- 3.StepCox[backward] + Enet[α=0.4] ---
--- 3.StepCox[backward] + Enet[α=0.5] ---
--- 3.StepCox[backward] + Enet[α=0.6] ---
--- 3.StepCox[backward] + Enet[α=0.7] ---
--- 3.StepCox[backward] + Enet[α=0.8] ---
--- 3.StepCox[backward] + Enet[α=0.9] ---
--- 3.StepCox[backward] + GBM ---
Error in serialize(data, node$con) : error writing to connection
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Error in serialize(data, node$con) : error writing to connection

**Comment by l-magnificence** [comment]
Please see #26
