### ISSUE TITLE
How can I extract the genes included in the machine learning model？

### ISSUE THREAD

**Issue by fujianhan** [l-magnificence/Mime#37]
Thanks for your impressive work. I have a question:
How can I extract the genes included in the machine learning combination with the highest C-index? For example, the genelist.Rdata in the sample data contains 42 genes. How can I extract the genes included in the model constructed by the StepCox[forward] + plsRcox combination?

**Comment by l-magnificence** [comment]
This model use the genes fitlerered by StepCox[forward] to construct model in plsRcox.  The genes fitlerered by StepCox[forward] are 
```
rownames(res[["ml.res"]][["StepCox[forward] + plsRcox"]][["pp"]])
```
In plsRcox, the original independent variables are transformed into a new set of synthetic variables, and then these synthetic variables are used for regression analysis. So the final plsRcox model is not simplyly defines as coefficient*gene expression, you can not extract gene's coefficient.
