### ISSUE TITLE
Error in running ML.Dev.Prog.Sig

### ISSUE THREAD

**Issue by zy-optimistic** [l-magnificence/Mime#44]
I got an error when running function ML.Dev.Prog.Sig with the parameter:
```
res <- ML.Dev.Prog.Sig(train_data = data$TCGA,
                       list_train_vali_Data = data,
                       unicox.filter.for.candi = T,
                       unicox_p_cutoff = 0.05,
                       candidate_genes = colnames(data$TCGA[-c(1:3)]),
                       mode = 'all',nodesize =5,seed = 5201314 )
```

The process was interrupted at 3.stepcox[both]:
Error in coxph(Surv(os.time, os) ~ RS，x)
    data contains an infinite predictor
Calls: ML.Dev.Prog.sig ... data,frame -> sapply -> lapply -> FUN -> summary -> coxph

**Comment by l-magnificence** [comment]
Do your data contain NA value?

**Comment by l-magnificence** [comment]
I think this error is due to the input data. If your data have infinite value, coxph will run error. Such as 
```
library(survival)
data<-data.frame("OS"=c(0,1,1,0,1),
                 "OS.time"=c(30,15,14,31,16),
                 "gene"=c(log(0),0,3,4,5))
coxph(Surv(OS.time, OS) ~ gene,data)
```
```
Error in coxph(Surv(OS.time, OS) ~ gene, data) : 
  data contains an infinite predictor
```

**Comment by l-magnificence** [comment]
Thank you for your feedback. I'm also confused about this. Personally, I think the power of model is significantly affected by many respects such as the number of gene and high variation of genes among sample. If a model is constructed using genes with low levels of variation and expression, even if the model is built, it is still difficult to calculate risk score for distinguishing between different samples. You can check the detailed information of constructed model and see the distribution of used genes in dataset. We need to constantly adjust the input data for improving the power of model.

**Comment by Link020303** [comment]
I also encountered this issue, and after checking the code, I found that it might be due to the data not being normalized. After I performed log2 normalization on my validation set data, the problem was resolved.
