### ISSUE TITLE
Request to upload a complete immunotherapy dataset

### ISSUE THREAD

**Issue by Mikebbbbb** [l-magnificence/Mime#47]
In the original study, the authors collated an immunotherapy dataset of 1042 patients from 18 cohorts for model training. But only 100 patient immunotherapy datasets were uploaded on GitHub. I would appreciate your generosity in uploading the full dataset.

**Comment by l-magnificence** [comment]
Only files related to packages are stored here and the datasets on Github are example for R package test. Detailed information of the immunotherapy dataset are described in supplementary table of paper, which you can access. Thank you.
