### ISSUE TITLE
Error in h(simpleError(msg, call))

### ISSUE THREAD

**Issue by yyypkw** [l-magnificence/Mime#48]
When I want to plot survival curve, I encounter this error. All data is from Example.cohort.Rdata and genelist.Rdata.

`>   print(survplot[[i]]<-rs_sur(res, model_name = "StepCox[forward] + plsRcox",dataset = names(list_train_vali_Data)[i],
+                               #color=c("blue","green"),
+                               median.line = "hv",
+                               cutoff = 0.5,
+                               conf.int = T,
+                               xlab="Day",pval.coord=c(1000,0.9)))
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'print': promise already under evaluation: recursive default argument reference or earlier problems?
In addition: Warning message:
In base::nchar(wide_chars$test, type = "width") :
  restarting interrupted promise `evaluation``

**Comment by l-magnificence** [comment]
Please show your object res and run code below to see if it can run.
```
rs_sur(res, model_name = "StepCox[forward] + plsRcox",dataset = names(list_train_vali_Data)[1],
                              #color=c("blue","green"),
                              median.line = "hv",
                              cutoff = 0.5,
                              conf.int = T,
                              xlab="Day",pval.coord=c(1000,0.9)))
```

**Comment by yyypkw** [comment]
@l-magnificence THANKS!! That works.
