### ISSUE TITLE
Can we add docker installation method?

### ISSUE THREAD

**Issue by zhangkaicr** [l-magnificence/Mime#52]
Thank you for writing the MIME package.I believe that many scholars will apply your package and cite your references.Your tutorial is very carefully written and provides example data.However, the installation of this package and other dependent packages may cause many problems due to the user's computer environment.If it is convenient for you, can you package the environment and related packages of your package into a docker image? If you do this, I will recommend your package and its docker image on all my and other public accounts I know. I believe that if you package the docker image, it will greatly promote the application of your package.

**Comment by l-magnificence** [comment]
Thank you for your suggestion. Due to heavy clinical work and other projects, this will be tested in the future, but not anytime soon.
