### ISSUE TITLE
After running, how to view the genes and correlation coefficients filtered under each model? Some models cannot display specific gene names and coef

### ISSUE THREAD

**Issue by Se-Any** [l-magnificence/Mime#55]
![微信图片_20240922104209](https://github.com/user-attachments/assets/56edd902-d63c-4d6c-9bb3-74aad5441938)
For example, this model

**Comment by l-magnificence** [comment]
As you know, not all model is simply defined as the sum of coefficient*expression. You need to learn the detailed structure of specific model from original method.
Please see #37 for example
